robot:
  type: ure

teleop:
  type: pose

task_topic: /lerobot_task

event_topic: /lerobot_event

bag_path: ../../../bags/lerobot_bag_2026_01_26-15_58_02

dataset:
  repo_id: "ngres/leros2-ur10e-cube"
  single_task: "Pick up the gray plush cube and put it into the gray box."
  fps: 30
  video: true
  push_to_hub: true


